### ISSUE TITLE
Integer printed as float

### ISSUE THREAD

**Issue by ahogen** [jongracecox/anybadge#25]
While looking at [`fixed-widths`](https://github.com/jongracecox/anybadge/tree/fix-widths) branch for #24, I noticed that integer values seemed to get marked as `float` instead of `int` as intended. Since it's a simple fix, I didn't think it needed a full PR, but I can make one if you'd like.

```diff
diff --git a/anybadge.py b/anybadge.py
index 5cc9f04..5dd00b3 100755
--- a/anybadge.py
+++ b/anybadge.py
@@ -307,12 +307,11 @@ class Badge(object):

         Returns: type
         """
+        if self.value_is_int:
+            return int
         if self.value_is_float:
             return float
-        elif self.value_is_int:
-            return int
-        else:
-            return str
+        return str

     @property
     def label_width(self):
```

Test:

```bash
python ./anybadge.py -l "test" -v "1234" -f ./test.svg -o
```

Before:
![before](https://user-images.githubusercontent.com/6827790/60947026-7901ad00-a2a4-11e9-84d1-ea7051ce26ea.PNG)

After fix:
![after](https://user-images.githubusercontent.com/6827790/60947029-7acb7080-a2a4-11e9-9463-fdbbfa2da537.PNG)

**Comment by jongracecox** [comment]
@ahogen Thanks for raising this issue, and the detail included.  I added a unit test to ensure that the `value_is_int` and `value_is_float` functions are working, but actually the `value_is_float` function returns True for an integer string, which is technically wrong (or at least wrong for the purposes that we want to use the function for).  I opted for updating the `value_is_float` function instead so that it returns False unless the value should be presented as a float on the badge value.

**Comment by ahogen** [comment]
I only recently learned how many string-like things look like a `float` to Python. Among the [values listed here](https://stackoverflow.com/a/20929881/3638827), I found these rather interesting....

```
Command to parse                        Is it a float?  Comment
--------------------------------------  --------------- ------------
print(isfloat("NaN"))                   True            nan is also float
print(isfloat("6e777777"))              True            This is same as Inf
print(isfloat("-iNF"))                  True
print(isfloat("infinity"))              True
print(isfloat(True))                    True            Boolean is a float
```

I haven't tried, but I don't *think* any of these things will create any weird badge output currently. But it was something I thought about briefly when I found this issue.

Cheers :slightly_smiling_face:
