### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '10.00'

### ISSUE THREAD

**Issue by llazzaro** [jongracecox/anybadge#27]
Today our CI broke with the latest version in pipy.
I saw some fix commits on the repo, not sure if it was published into pipy.

Thanks!

```
Traceback (most recent call last):
  File "/builds/faradaysec/faraday/faraday_venv/bin/anybadge", line 10, in <module>
    sys.exit(main())
  File "/builds/faradaysec/faraday/faraday_venv/local/lib/python2.7/site-packages/anybadge.py", line 755, in main
    value_format=args.value_format, text_color=args.text_color)
  File "/builds/faradaysec/faraday/faraday_venv/local/lib/python2.7/site-packages/anybadge.py", line 191, in __init__
    value_text = str(self.value_type(value))
ValueError: invalid literal for int() with base 10: '10.00'
```

**Comment by redorff** [comment]
I have got the same issue with '10.0' ;)

**Comment by nthexwn** [comment]
This was working on 1.4.0.  I'm running into the same issue with Friday's 1.5.0 update when passing Pylint output to Anybadge using Bash:

    # Retrieve pylint score from log file
    score=$(sed -n "s/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p" <<< "$output" || true)

    # Round score down (workaround)
    score="${score%.*}"

**Comment by raabf** [comment]
Can confirm. The error always happens when the decimal places are only zeros (It still works for example with `10.01`).

**Comment by jongracecox** [comment]
I updated the `value_is_int` function to return False when there is a `.` present in the value. This fixes the error.

Here is a badge generated with the fix.  This was generated with:

```python
badge = Badge('test', value='10.00')
```

Note that the zeros are truncated to just 1.

![image](https://user-images.githubusercontent.com/30441316/61331730-7ba65a00-a7f0-11e9-891a-32509d8dcf61.png)

This did all make me wonder why the value needs to be type-cast at all.  If we assumed it was a string then we could just use it as-is.  This felt like it could have repercussions, so I would be nervous about making that kind of change.

**Comment by jongracecox** [comment]
This is fixed in 1.5.1.

**Comment by nthexwn** [comment]
"If we assumed it was a string then we could just use it as-is. This felt like it could have repercussions, so I would be nervous about making that kind of change."

Would this affect the logic for determining a background color based on the numerical value?

**Comment by jongracecox** [comment]
> Would this affect the logic for determining a background color based on the numerical value?

Ah, I missed the obvious.  Yes, it would.
