### ISSUE TITLE
Add documentation on how to include emojis

### ISSUE THREAD

**Issue by roipoussiere** [jongracecox/anybadge#43]
It could be nice to support emojis in badges.

My use case is that I often create badges for simple links, and in this case the label could just be the emoji 🔗:

    anybadge --label='🔗' --value='doc' --color=orange
    anybadge --label='🔗' --value='pypi' --color=blue

But it could be used for other use cases.

**Comment by jongracecox** [comment]
I like this idea.  I'm not sure how it would work, but I will look into it.  Please share any ideas.  I guess the easiest approach would be to use an embedded emoji image via URL within the SVG file.

**Comment by roipoussiere** [comment]
We could also include svg of emojis in the lib (there are several ope-source svg sets, such as Twemoji), and include it in the badge, in order to make the badge self-sufficient.

**Comment by jongracecox** [comment]
Interestingly I just ran the following commands to test whether emjois already work:

```
./anybadge.py -l "🎯 Some thing" -v 23 -f test_emoji.svg
./anybadge.py -l "🔗" -v "Documentation" -f test_emoji_link.svg
```

In this case I copied and pasted system emojis and used them in the commands.  This produced the following SVG files:

![image](https://user-images.githubusercontent.com/30441316/87602015-39924b80-c6c4-11ea-8d96-f33524e43171.png)
![image](https://user-images.githubusercontent.com/30441316/87601999-2f704d00-c6c4-11ea-843d-8888385b6c47.png)

The generated SVG text contains the raw emoji character, so will be left to the viewers browser to interpret and display, but I think most common emojis will be available by default.

This is the generated SVG:

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="147" height="20">
    <linearGradient id="b" x2="0" y2="100%">
        <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
        <stop offset="1" stop-opacity=".1"/>
    </linearGradient>
    <mask id="anybadge_1">
        <rect width="147" height="20" rx="3" fill="#fff"/>
    </mask>
    <g mask="url(#anybadge_1)">
        <path fill="#555" d="M0 0h50v20H0z"/>
        <path fill="#4c1" d="M50 0h97v20H50z"/>
        <path fill="url(#b)" d="M0 0h147v20H0z"/>
    </g>
    <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
        <text x="26" y="15" fill="#010101" fill-opacity=".3">🔗</text>
        <text x="25" y="14">🔗</text>
    </g>
    <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
        <text x="99" y="15" fill="#010101" fill-opacity=".3">Documentation</text>
        <text x="98" y="14">Documentation</text>
    </g>
</svg>
```

I know it would be more consistent and reliable to embed the emoji image into the SVG output, but this might be "good enough" and not create more code to support.  What do you think?

**Comment by roipoussiere** [comment]
Yes I think your solution is good enough.

**Comment by jongracecox** [comment]
What do you say? Maybe update the documentation with how to do this?

**Comment by roipoussiere** [comment]
Ok, I got it. The svg viewer builtin in my IDE (PyCharm) don't shows emojis in svg texts. So I supposed that it was not possible and created this issue, but the badge is correctly rendered on Firefox and on my system's svg viewer.

> Maybe update the documentation with how to do this?

Yes, and add a note about badge rendering that might fail on some svg viewers. ;)

Also, some IDEs might sucks at displaying emojis in the code, so we may think about including emojis codes supports, just like in GitHub and other places, ie `:link:` -> :link:. The [emoji package](https://pypi.org/project/emoji/) is relevant in that case, but I can create an other issue for this.
