### ISSUE TITLE
Feature Request: SemVer support for thresholds

### ISSUE THREAD

**Issue by remy-tiitre** [jongracecox/anybadge#45]
It would be a nice touch to be able to add semver as thresholds in a pattern "-c green 2.4.5=orange 2.4.0=red" so that anything below or equal to 2.4.0 would be red, anything between 2.4.5 and 2.4.0 would be orange and anything over 2.4.5 (2.4.6 for example) would be green.

**Comment by jongracecox** [comment]
Hi @remy-tiitre, I just added a PR for semver support. Would you be interested in testing it out? I'm pretty confident in the change, but I would like to see how it fits with your use-case.

**Comment by remy-tiitre** [comment]
I kind of implemented it with my own python script already as well. But how can I test it, its probably not in released version yet?

**Comment by jongracecox** [comment]
> I kind of implemented it with my own python script already as well. But how can I test it, its probably not in released version yet?

You would need to clone the repo, and switch to the feature branch:

```bash
git clone git@github.com:jongracecox/anybadge.git
cd anybadge
git checkout jongracecox/feature-add-semver-support
```

You could just take a look at the PR here, which includes some detail: https://github.com/jongracecox/anybadge/pull/46

If you think it looks good I can merge it and create a release candidate which you could play with more easily by pip installing.

**Comment by jongracecox** [comment]
@remy-tiitre, I took the liberty of cutting a [1.8.0rc1 release candidate](https://github.com/jongracecox/anybadge/releases/tag/1.8.0rc1), which you can install with 

```bash
pip install anybadge==1.8.0rc1
```

**Comment by jongracecox** [comment]
Hi @remy-tiitre, are you still interested in testing the semver support I added? If not, I will go ahead and cut a release with this current implementation and close the issue - I was just hoping to get your feedback.

**Comment by jongracecox** [comment]
Closing as this has been implemented.
