### ISSUE TITLE
Thoughts on splitting out into modules

### ISSUE THREAD

**Issue by miff2000** [jongracecox/anybadge#51]
Hey!

First of all, thanks for creating this! It's fantastic and is really simple to use / import. I also love the fact you included a webserver for it, ace!

I wanted to ask, what your thoughts are on splitting out the single `anybadge.py` file into separate files? You'll see I've added PR #50 to support a new format called `GitLab Scoped`, and would like to add other formats in future. As the file will grow exponentially as a result, it seemed to me to be a good time to externalise the `Badge` class.

We can then add other classes (e.g., `GitLabScopedBadge`) easily and import the class as needed, perhaps based on the `--style` flag.

I don't want to set off and do that work though unless you're happy and the PR is likely to be accepted of course 🙂

Let me know what you think anyway.

Cheers

**Comment by jongracecox** [comment]
I like this idea, and have some plans for it. I can push a PR and let you take a look to see if I miss anything that you think would be useful. I'm also thinking of dropping Python 2.7 support to allow for more creativity.

**Comment by miff2000** [comment]
Yeah, that sounds great :)

Dropping 2.7 support I'd totally agree with. Most currently supported Linux distros ship with (or have repositories that carry) Python 3.6 onwards, so should be safe in most cases

**Comment by jongracecox** [comment]
@miff2000, I've dropped an PR for switching to a package with submodules, and pkg_resources for the SVG templates. See what you think.

Something else I would like to do after getting this change in is switching to using Jinja2 for resolving the templates. This way it would be easy to set default attributes (e.g. colors) directly within the templates, and potentially use Jinja2 logic (although I can't think what for at the moment).

**Comment by miff2000** [comment]
I've had a look over it. It all looks good to me! I can see you've touched up a load of other stuff too - awesome!!

Two questions I have now are:

* **What do you think to making the style responsible for some of the calculations?**
  It's likely that, at some point, you'd need extra padding or maybe to offset the text to make space for an image. If we passed the calculated text width to the style, it could work out any of the nuances required to make the text (or images) appear correctly. 
  This could be done with Jinja2 math functions, but it feels hackier than just having the style class deal with it.

* **How do we work with single or even triple word badges?**
  For GitLab, at least, most badges (they call them labels) are a single word. We should work out how to support that situation and up to N words. They could be passed to the style in a list and the style class work out where they should go in the badge.

**Comment by jongracecox** [comment]
> I've had a look over it. It all looks good to me! I can see you've touched up a load of other stuff too - awesome!!
> 
> Two questions I have now are:
> 
> * **What do you think to making the style responsible for some of the calculations?**
>   It's likely that, at some point, you'd need extra padding or maybe to offset the text to make space for an image. If we passed the calculated text width to the style, it could work out any of the nuances required to make the text (or images) appear correctly. Properties like `badge_width`, `value_anchor`, `label_anchor`, `color_split_position`, etc.
>   This could be done with Jinja2 math functions, but it feels hackier than just having the style class deal with it.
> * **How do we work with single or even triple word badges?**
>   For GitLab, at least, most badges (they call them labels) are a single word. We should work out how to support that situation and up to N words. They could be passed to the style in a list and the style class work out where they should go in the badge.

@miff2000 These are good ideas - lets put these in a new issue so I can close this one. I've merged the package structure changes and these are available in 1.11.0, so this stuff could all come next.
