### ISSUE TITLE
Drop Python<3.5 and introduce type hints

### ISSUE THREAD

**Issue by eggplants** [jongracecox/anybadge#55]
**Is your feature request related to a problem? Please describe.**
When using your awesome project in typed project/library, it is better that anybadge is typed strictly.

**Describe the solution you'd like**
I think package's `python_requires` should be `>=3.7` (or at least `>=3.5`) to add type hints and drop EOL'd versions.
And I suggest to setup mypy (or pyre) with setup.cfg and add it to CI steps.

**Comment by jongracecox** [comment]
Re-opening as I agree with this request. Not having type hints makes me sad.

**Comment by jongracecox** [comment]
Implemented as part of #59

**Comment by eggplants** [comment]
typed marker (`py.typed`) would be helpful for the projects using anybadge.

https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages
