### ISSUE TITLE
question - how to produce badge like label : text

### ISSUE THREAD

**Issue by georgesuba** [jongracecox/anybadge#87]
Hi, just a question.. somehow I am unable to produce simple texted badge like: 

label : value_as_any_text something like this: 

![text badge](https://raw.githubusercontent.com/jongracecox/anybadge/master/examples/color_blueviolet.svg)

I've tried in terminal but got back error message that -v is expected to be number. If someone can point me in right direction what I am missing here, that would be fantastic. Thank you.

**Comment by jongracecox** [comment]
There's no restriction on values. You should be able to generate the badge you shared in your example using the following command in the console:

```bash
anybadge --label "Color" --value "blueviolet" --color BLUEVIOLET --file badge.svg
```

Could you share the version of anybadge you're using, the command you ran and the exact output you got?

**Comment by georgesuba** [comment]
@jongracecox 

Hi, oh moment of embarrassment! I see now what I was doing wrong (I messed my command with single and double quotes) - my bad.

Your command indeed worked. I am on version v1.14.0. Since error was on my end and not with anybadge I am sorry for this and closing this embarrassing question. Thank you very much!

**Comment by jongracecox** [comment]
I'm happy you worked it out! I'm interested in how your error came about since quoting should affect the outcome. All the commands below should all be valid. Maybe you would consider sharing your command so others can learn from it.

```bash
python -m anybadge --label "Color" --value "blueviolet" --color BLUEVIOLET --file badge.svg -o
python -m anybadge --label 'Color' --value 'blueviolet' --color BLUEVIOLET --file badge.svg -o
python -m anybadge --label Color --value blueviolet --color BLUEVIOLET --file badge.svg -o
```
