### ISSUE TITLE
Ability to generate only value badges

### ISSUE THREAD

**Issue by jmarcelomb** [jongracecox/anybadge#89]
Right now if I try to generate a badge with an empty label, it is going to be this way:
![image](https://github.com/jongracecox/anybadge/assets/35546901/35466d72-2eec-4a42-a9c1-f6eed9a8297e)

It is possible to generate without the gray part? 

Thank you!

**Comment by jongracecox** [comment]
This wasn't too complicated to do. I've got a PR open (#90), but need to do some work before releasing it as the Travis deployment process isn't working and needs porting over to GitHub actions.

**Comment by jongracecox** [comment]
@jmarcelomb, it's taken me a while to get around to it, but this is available in [v1.15.6](https://github.com/jongracecox/anybadge/releases/tag/v1.15.6)
